import React from 'react';
import { AlertTriangle } from 'lucide-react';

const WeakAreas = () => {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-white flex items-center space-x-3">
        <AlertTriangle className="w-7 h-7 text-amber-400" />
        <span>Weak Areas & Remediation Engine</span>
      </h1>
      <div className="glass-panel p-6 rounded-2xl border border-gray-800">
        <p className="text-gray-300 text-sm">Automated weakness detection alerts and personalized drill recommendations generated by analyzing your error taxonomy and time metrics.</p>
      </div>
    </div>
  );
};

export default WeakAreas;
